// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://vtjntc7hznfi7o3xhzn4ki4m64.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b2iakohve5gcrlzsujd27x5u3a",
    "aws_cognito_identity_pool_id": "us-east-1:e3e3c239-33cd-4644-b948-20edc3d1e6e5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9GktVGW3m",
    "aws_user_pools_web_client_id": "3k3ljnj01ht1es23ganhmt5qfp",
    "oauth": {}
};


export default awsmobile;
